const PRODUCTS = [
    {id:1,name:"Interactive Feather Wand",category:"toys",icon:"🪶",bestFor:"Interactive play",description:"A simple wand-style toy for supervised play sessions.",retailer:"Chewy",url:"#"},
    {id:2,name:"Motion-Activated Cat Toy",category:"toys",icon:"⚙️",bestFor:"Curious cats",description:"An electronic-style toy concept for cats who enjoy movement.",retailer:"Amazon",url:"#"},
    {id:3,name:"Catnip Plush Toy",category:"toys",icon:"🧸",bestFor:"Solo play",description:"A soft toy option for cats that enjoy catnip.",retailer:"Chewy",url:"#"},
    {id:4,name:"Ball Track Toy",category:"toys",icon:"🎾",bestFor:"Indoor activity",description:"A contained rolling-toy concept for independent play.",retailer:"Amazon",url:"#"},
    {id:5,name:"Interactive Puzzle Feeder",category:"toys",icon:"🧩",bestFor:"Mental enrichment",description:"A puzzle-style feeder that can make mealtime more engaging.",retailer:"Petco",url:"#"},
    {id:6,name:"Multi-Level Cat Tree",category:"furniture",icon:"🌳",bestFor:"Climbing & lounging",description:"A vertical furniture option with platforms and resting areas.",retailer:"Chewy",url:"#"},
    {id:7,name:"Tall Scratching Post",category:"furniture",icon:"🪵",bestFor:"Scratching",description:"A vertical scratching option for cats that like to stretch.",retailer:"Amazon",url:"#"},
    {id:8,name:"Corrugated Scratching Pad",category:"furniture",icon:"📦",bestFor:"Horizontal scratching",description:"A low-profile scratching surface for floor-level play.",retailer:"Chewy",url:"#"},
    {id:9,name:"Cozy Cat Bed",category:"furniture",icon:"🛏️",bestFor:"Napping",description:"A dedicated resting spot for cats that like soft surfaces.",retailer:"Petco",url:"#"},
    {id:10,name:"Window Cat Perch",category:"furniture",icon:"🪟",bestFor:"Window watching",description:"A perch concept that gives cats an elevated viewing spot.",retailer:"Amazon",url:"#"},
    {id:11,name:"Automatic Cat Feeder",category:"feeding",icon:"🍽️",bestFor:"Scheduled meals",description:"A timed-feeding option for households that want automated portions.",retailer:"Chewy",url:"#"},
    {id:12,name:"Stainless Steel Water Fountain",category:"feeding",icon:"💧",bestFor:"Water station",description:"A fountain-style water station designed for everyday use.",retailer:"Amazon",url:"#"},
    {id:13,name:"Elevated Cat Bowls",category:"feeding",icon:"🥣",bestFor:"Mealtime",description:"Raised bowl setup for cats whose owners prefer an elevated station.",retailer:"Petco",url:"#"},
    {id:14,name:"Slow Feeder Bowl",category:"feeding",icon:"🐌",bestFor:"Fast eaters",description:"A maze-style bowl intended to slow down eating.",retailer:"Chewy",url:"#"},
    {id:15,name:"Airtight Food Storage Container",category:"feeding",icon:"🫙",bestFor:"Food storage",description:"A storage option for keeping dry food contained between meals.",retailer:"Amazon",url:"#"},
    {id:16,name:"Large Open Litter Box",category:"litter",icon:"🧺",bestFor:"Everyday litter setup",description:"A roomy traditional litter-box format.",retailer:"Chewy",url:"#"},
    {id:17,name:"Automatic Self-Cleaning Litter Box",category:"litter",icon:"🤖",bestFor:"Automation",description:"An automated litter-box category for owners seeking less scooping.",retailer:"Petco",url:"#"},
    {id:18,name:"High-Sided Litter Box",category:"litter",icon:"⬆️",bestFor:"Mess reduction",description:"A high-sided design intended to help contain litter.",retailer:"Amazon",url:"#"},
    {id:19,name:"Litter Tracking Mat",category:"litter",icon:"🧼",bestFor:"Floor cleanup",description:"A mat designed to catch loose litter near the box.",retailer:"Chewy",url:"#"},
    {id:20,name:"Metal Litter Scoop",category:"litter",icon:"🥄",bestFor:"Daily scooping",description:"A durable scoop option for routine litter-box cleanup.",retailer:"Amazon",url:"#"},
    {id:21,name:"Deshedding Cat Brush",category:"grooming",icon:"🪮",bestFor:"Loose fur",description:"A brushing tool for removing loose hair during grooming.",retailer:"Chewy",url:"#"},
    {id:22,name:"Soft Grooming Glove",category:"grooming",icon:"🧤",bestFor:"Gentle brushing",description:"A glove-style grooming option for cats that dislike traditional brushes.",retailer:"Amazon",url:"#"},
    {id:23,name:"Cat Nail Clippers",category:"grooming",icon:"✂️",bestFor:"Nail care",description:"A small clipper designed for routine at-home nail care.",retailer:"Petco",url:"#"},
    {id:24,name:"Cat Toothbrush Kit",category:"grooming",icon:"🪥",bestFor:"Dental routine",description:"A starter-style dental-care kit for owners following a home routine.",retailer:"Chewy",url:"#"},
    {id:25,name:"Cat Grooming Kit",category:"grooming",icon:"🧴",bestFor:"Home grooming",description:"A multi-tool grooming option for owners building a home kit.",retailer:"Amazon",url:"#"},
    {id:26,name:"Hard-Sided Cat Carrier",category:"travel",icon:"🧳",bestFor:"Vet trips",description:"A structured carrier option for transportation.",retailer:"Chewy",url:"#"},
    {id:27,name:"Adjustable Cat Harness",category:"travel",icon:"🦺",bestFor:"Leash training",description:"A harness option for owners who want to explore supervised outdoor activities.",retailer:"Petco",url:"#"},
    {id:28,name:"Pet GPS Tracker",category:"travel",icon:"📍",bestFor:"Location tracking",description:"A GPS-tracking category for owners considering extra location awareness.",retailer:"Amazon",url:"#"},
    {id:29,name:"Cat Travel Backpack",category:"travel",icon:"🎒",bestFor:"Portable travel",description:"A backpack-style carrier category for selected travel situations.",retailer:"Chewy",url:"#"},
    {id:30,name:"Breakaway Cat Collar",category:"travel",icon:"🏷️",bestFor:"Everyday identification",description:"A breakaway-style collar option for identification and accessories.",retailer:"Petco",url:"#"}
    ];
